package com.aere.spring.mybatis.model;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_id
     *
     * @mbggenerated Thu May 26 16:17:21 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_name
     *
     * @mbggenerated Thu May 26 16:17:21 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_birthday
     *
     * @mbggenerated Thu May 26 16:17:21 CST 2016
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_salary
     *
     * @mbggenerated Thu May 26 16:17:21 CST 2016
     */
    private Double salary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_access_time
     *
     * @mbggenerated Thu May 26 16:17:21 CST 2016
     */
    private Date accessTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_id
     *
     * @return the value of t_user.user_id
     *
     * @mbggenerated Thu May 26 16:17:21 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_id
     *
     * @param id the value for t_user.user_id
     *
     * @mbggenerated Thu May 26 16:17:21 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_name
     *
     * @return the value of t_user.user_name
     *
     * @mbggenerated Thu May 26 16:17:21 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_name
     *
     * @param name the value for t_user.user_name
     *
     * @mbggenerated Thu May 26 16:17:21 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_birthday
     *
     * @return the value of t_user.user_birthday
     *
     * @mbggenerated Thu May 26 16:17:21 CST 2016
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_birthday
     *
     * @param birthday the value for t_user.user_birthday
     *
     * @mbggenerated Thu May 26 16:17:21 CST 2016
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_salary
     *
     * @return the value of t_user.user_salary
     *
     * @mbggenerated Thu May 26 16:17:21 CST 2016
     */
    public Double getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_salary
     *
     * @param salary the value for t_user.user_salary
     *
     * @mbggenerated Thu May 26 16:17:21 CST 2016
     */
    public void setSalary(Double salary) {
        this.salary = salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_access_time
     *
     * @return the value of t_user.user_access_time
     *
     * @mbggenerated Thu May 26 16:17:21 CST 2016
     */
    public Date getAccessTime() {
        return accessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_access_time
     *
     * @param accessTime the value for t_user.user_access_time
     *
     * @mbggenerated Thu May 26 16:17:21 CST 2016
     */
    public void setAccessTime(Date accessTime) {
        this.accessTime = accessTime;
    }
}